version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  static-tests:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm run lint
  components-tests:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm run test -p ButtonIcon
  views-tests:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm run test -p Home
workflows:
    build:
      jobs:
        - build
    tests:
      jobs:
        - static-tests:
        - components-tests:
            requires:
            - static-tests:
        - views-tests:
            requires:
              - components-tests
