version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  dependiences:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  static-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
  components-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test -p ButtonIcon
  views-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test -p Home
  build-deploy:
    docker:
      - image: node:11.10.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - run: npm run build
      - run: npx netlify deploy --prod
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npx netlify deploy --prod
workflows:
  version: 2
  build-tests:
    jobs:
      - dependiences
      - static-tests:
          requires:
            - dependiences
      - components-tests:
          requires:
            - dependiences
      - views-tests:
          requires:
            - dependiences
      - hold:
          type: approval
          requires:
            - static-tests
            - components-tests
            - views-tests
      - build-deploy:
          requires:
            - hold
