version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  dependiences:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  static-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
  components-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test -p ButtonIcon
  views-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test -p Home
  deploy:
    docker:
      - image: node:11.10.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm install netlify-cli -g
      - run: netlify deploy --prod --dir build --auth acdccc8efc3c17ec84a54bee2944ae9c2027d438fabf93a2cc787857a29623fe --site bf2810cb-230b-49f4-9721-1c8971fae473
workflows:
  version: 2
  build-tests:
    jobs:
      - dependiences
      - static-tests:
          requires:
            - dependiences
      - components-tests:
          requires:
            - dependiences
      - views-tests:
          requires:
            - dependiences
      - hold:
          type: approval
          requires:
            - static-tests
            - components-tests
            - views-tests
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
